name: Build and Deploy
on:
  push:
    branches: [ main ] 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' 
      - name: Build
        run: ./gradlew build 
      - name: Test
        run: ./gradlew test 
      - name: Deploy
        uses: appleboy/ssh-action@master 
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USUARIO }} 
          password: ${{ secrets.SENHA }}
          script: |
